[project]
name = "llmprof"
version = "0.1.0"
description = "Inference profiler for local LLMs"
requires-python = ">=3.12,<3.14"

dependencies = [
    "typer",
    "httpx"
]

[project.optional-dependencies]
dev = [
    "black",
    "ruff",
    "mypy",
    "pytest",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
llmprof = "llmprof.cli:app"